lrz/lrz_datapool/datapool/urls.py
from django.conf.urls import url
from datapool import views


urlpatterns = [
    url(r'^$',
        views.main_views.index_view,
        name='index'
        ),

    # D A T A P O O L
    # function-based view
    url(r'^datapool/list/$',
        views.datapool_views.datapool_list_view,
        name='datapool_list'
        ),
    url(r'^datapool/(?P<pk>\d+)/$',
        views.datapool_views.datapool_detail_view,
        name='datapool_detail'
    ),
    # url(r'^datapool/create/$',
    #     views.datapool_views.datapool_create_view,
    #     name='datapool_create'
    #     ),
    # url(r'^datapool/delete/(\d+)/$',
    #     views.datapool_views.datapool_delete_view,
    #     name='datapool_delete'
    #     ),
    #this is a duplicate of the class-based update-view blow
    #url(r'^datapool/updateF/(\d+)/$',
    #    views.datapool_views.datapool_update_view,
    #    name='datapool_update_f'
    #    ),

    # class-based view
    url(r'^datapool/create/$',
        views.datapool_views_cb.Datapool_create_view.as_view(),
        name='datapool_create'
        ),
    url(r'^datapool/delete/(?P<pk>\d+)/$',
        views.datapool_views_cb.Datapool_delete_view.as_view(),
        name='datapool_delete'
    ),
    url(r'^datapool/updateC/(?P<pk>\d+)/$',
        views.datapool_views_cb.Datapool_update_view.as_view(),
        name='datapool_update'
    ),

    # P R O J E C T
    url(r'^project/list/$',
        views.project_views.ProjectListView.as_view(),
        name="project_list"
    ),
    url(r'^project/create/$',
        views.project_views.ProjectCreateView.as_view(),
        name="project_create"
    ),
    url(r'^project/(?P<pk>\d+)/$',
        views.project_views.ProjectDetailView.as_view(),
        name='project_detail'
    ),
    url(r'^project/update/(?P<pk>\d+)/$',
        views.project_views.ProjectUpdateView.as_view(),
        name='project_update'
    ),
    url(r'^project/delete/(?P<pk>\d+)/$',
        views.project_views.ProjectDeleteView.as_view(),
        name='project_delete'
    ),

    # Q U O T A
    url(r'^quota/create/forProject/(?P<project_id>\d+)/$',
        views.quota_views.QuotaCreateView.as_view(),
        name='quota_create'
    ),
    url(r'^quota/update/(?P<pk>\d+)/$',
        views.quota_views.QuotaUpdateView.as_view(),
        name='quota_update'
    ),
    url(r'^quota/delete/(?P<pk>\d+)/$',
        views.quota_views.QuotaDeleteView.as_view(),
        name='quota_delete'
    ),

    # C O N T A I N E R
    url(r'^container/list/Qt/(?P<quotaID>\d+)/$',
        views.container_views.ContainerListView.as_view(),
        name="container_list"
    ),
    url(r'^container/list/Qt/(?P<quotaID>\d+)/asSnippet/$',
        views.container_views.ContainerListSnippetView.as_view(),
        name="container_list_snippet"
    ),
    url(r'^container/create/forProject/(?P<projectID>\d+)/$',
        views.container_views.ContainerCreateView.as_view(),
        name="container_create_forProject"
    ),
    url(r'^container/create/onQuota/(?P<quotaID>\d+)/$',
        views.container_views.ContainerCreateView.as_view(),
        name="container_create_onQuota"
    ),
    url(r'^container/update/(?P<pk>\d+)/$',
        views.container_views.ContainerUpdateView.as_view(),
        name="container_update"
    ),
    url(r'^container/delete/(?P<pk>\d+)/$',
        views.container_views.ContainerDeleteView.as_view(),
        name="container_delete"
    ),

]

lrz/lrz_datapool/project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', auth_views.LoginView.as_view(), name='login'),
    url(r'^logout/', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^datapool/', include('datapool.urls', namespace='datapool')),
    # no namespace here. giving that will break the serializer's 'url'-field magic
    url(r'^datapool_api/', include('datapool_api.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]


# D E B U G   T O O L B A R
from django.conf import settings
from django.conf.urls import include, url

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

lrz/lrz_datapool/datapool/models/project.py
from django.db import models

class Project(models.Model):
    name = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def countDatapoolsLinked(self):
        from datapool.models.quota import Quota
        return Quota.objects.filter(project=self).count()

lrz/lrz_datapool/datapool/forms.py
from django import forms
from datapool.models import Quota, Datapool, Container

class CreateQuotaForm(forms.ModelForm):
    class Meta:
        model = Quota
        # project nicht, das wird extern festgelegt und kann vom user nicht geändert werden.
        fields = ['datapool', 'space']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # find out which datapools already have a quota for this project.
        usedDatapoolIds = Quota\
            .objects\
            .filter(project=self.instance.project)\
            .values_list('datapool__id', flat=True)

        # each project can only have one quota per datapool,
        # so limit the list of datapools to create a new quota for
        # to the datapools which dont have a quota for this project yet.
        unconnectedDatapools = Datapool.objects.all().exclude(id__in=usedDatapoolIds)
        # save that into the field
        self.fields['datapool'].queryset = unconnectedDatapools

    def clean_quota(self):
        if self.cleaned_data['space'] < 1:
            raise forms.ValidationError('Quota-space value must be 1 or greater.')
        return self.cleaned_data['space']


class CreateContainerForm(forms.ModelForm):
    class Meta:
        model = Container
        fields = ['name', 'space', 'quota']


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        try:# if quota is already set, use that and do not allow the user to change it
            self.instance.quota #  will cause an exception if quota is not set
            #self.fields['quota'].widget.attrs['readonly'] = True
            self.fields['quota'].widget = forms.HiddenInput()
        except: # if quota is not yet set via params, restrict choice to quotas of this project
            #how to get stuff to herer?
            pass#self.fields['quota'].queryset = Quota.objects.filter(project_id=self.data['projectID'])

lrz/lrz_datapool/datapool/views/container_views.py
from django.views import generic
from django.shortcuts import get_object_or_404, reverse

from datapool.models import Datapool
from datapool.models.container import Container
from datapool.models.quota import Quota
from datapool.models.project import Project
from datapool.forms import CreateContainerForm

class ContainerListTemplate(generic.ListView):
    model = Container
    fields = ['name', 'quota', 'space', 'used', 'updated', 'created', ]
    template_name = 'datapool/container/list.html'
    context_object_name = 'containers'

    def dispatch(self, request, *args, **kwargs):
        self.quota = get_object_or_404(Quota, pk=self.kwargs['quotaID'])
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return self.quota.container_set.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['project']  = self.quota.project
        context['datapool'] = self.quota.datapool
        context['quota'] = self.quota
        context['used'] = self.quota.space - self.quota.spaceLeft()
        context['free'] = self.quota.spaceLeft()
        return context


class ContainerListView(ContainerListTemplate):
    pass

class ContainerListSnippetView(ContainerListTemplate):
    template_name = 'datapool/container/listSnippet.html'


class ContainerCreateView(generic.CreateView):
    model = Container
    template_name = 'datapool/container/create.html'
    context_object_name = 'container'
    form_class = CreateContainerForm

    def dispatch(self, request, *args, **kwargs):
        self.quota   = None
        self.project = None

        if 'quotaID' in self.kwargs:
            quotaID = self.kwargs['quotaID']
            self.quota = get_object_or_404(Quota, pk=quotaID)
        elif 'projectID' in self.kwargs:
            self.project = get_object_or_404(Project, pk=self.kwargs.get('projectID'))
        else:
            raise Exception("How did that happen? we should have either quota or project here.")

        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['quota']   = self.quota
        context['project'] = self.project
        return context


    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if self.quota:
            kwargs['instance'] = Container(quota=self.quota)
        return kwargs

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        if self.project:
            form.fields['quota'].queryset = Quota.objects.filter(project_id=self.project)
        return form

    def get_success_url(self):
        if self.project:
            return reverse('datapool:project_detail', kwargs=dict(pk=self.project.id))
        if self.quota:
            return reverse('datapool:container_list', kwargs=dict(quotaID=self.quota.id,))


class ContainerUpdateView(generic.UpdateView):
    model = Container
    fields = ['name', 'quota', 'space', ]
    template_name = 'datapool/container/update.html'
    context_object_name = 'container'
    def get_success_url(self):
        return reverse('datapool:container_list', kwargs=dict(quotaID=self.object.quota.id,))


class ContainerDeleteView(generic.DeleteView):
    model = Container
    fields = ['name', 'quota', 'space', ]
    template_name = 'datapool/container/delete.html'
    context_object_name = 'container'
    def get_success_url(self):
        return reverse('datapool:container_list', kwargs=dict(quotaID=self.object.quota.id,))

lrz/lrz_datapool/datapool/views/datapool_views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from datapool.models import Datapool
from django.forms import modelform_factory
from django.views import generic

allFields=['name', 'description', 'space', 'pool_type', 'owner',]

def datapool_list_view(request):
    pools = Datapool.objects.all()
    context = dict(pools=pools)
    return render(request, 'datapool/datapool/datapool_list.html', context)


def datapool_create_view(request):
    formclass = modelform_factory(Datapool, fields=allFields)

    if request.method == 'POST':
        form = formclass(request.POST)
        if form.is_valid():
            datapool = form.save()
            return redirect(reverse('datapool:datapool_list'))
        else:
            pass # if invalid just fall through to the last return. but now it has error-annotations.
    else:
        form = formclass()

    context = dict(
        form=form,
    )

    return render(request, 'datapool/datapool/datapool_create.html', context)


def datapool_detail_view(request, pk):
    datapool = get_object_or_404(Datapool, pk=pk)
    context = dict(
        datapool = datapool
    )
    return render(request, 'datapool/datapool/datapool_detail.html', context)


def datapool_update_view(request, pk):
    pool = get_object_or_404(Datapool, pk=pk)
    formclass = modelform_factory(Datapool, fields=['name', 'description', 'pool_type', 'owner',])

    if request.method == 'POST':
        form = formclass(request.POST, instance=pool)
        if form.is_valid():
            datapool = form.save()
            return redirect(reverse('datapool:datapool_list'))
        else:
            pass # if invalid just fall through to the last return. but now it has error-annotations.
    else:
        form = formclass(instance=pool)

    context = dict(
        form=form,
        datapool=pool,
    )

    return render(request, 'datapool/datapool/datapool_update.html', context)


def datapool_delete_view(request, pk):
    """This thing instantly deletes instances. beware!"""
    pool = get_object_or_404(Datapool, pk=pk)
    pool.delete()

    return redirect(reverse('datapool:datapool_list'))

lrz/lrz_datapool/datapool/views/datapool_views_cb.py
from django.shortcuts import reverse
from django.views import generic
from datapool.models import Datapool

allFields=['name', 'description', 'space', 'pool_type', 'owner',]

class Datapool_create_view(generic.CreateView):
    model = Datapool
    template_name = 'datapool/datapool/datapool_create.html'
    context_object_name = 'datapool'
    fields = allFields

    def get_success_url(self):
        return reverse('datapool:datapool_list')


class Datapool_update_view(generic.UpdateView):
    model = Datapool
    template_name = 'datapool/datapool/datapool_update.html'
    context_object_name = 'datapool'
    fields = allFields

    def get_success_url(self):
        context = dict(pk=self.object.id)
        return reverse('datapool:datapool_update', kwargs=context)



class Datapool_delete_view(generic.DeleteView):
    model = Datapool
    template_name = 'datapool/datapool/datapool_delete.html'
    context_object_name = 'datapool'
    fields = allFields

    def get_success_url(self):
        return reverse('datapool:datapool_list')

lrz/lrz_datapool/datapool/views/main_views.py
from django.shortcuts import render
from datapool import models as dp_models

# Create your views here.

def index_view(request):

    pools = dp_models.Datapool.objects.all()
    context = dict(
        pools=pools,
    )

    return render(request, 'datapool/index.html', context)

lrz/lrz_datapool/datapool/views/project_views.py
from django.shortcuts import reverse
from django.views import generic
from datapool.models.project import Project
from datapool.models.quota import Quota

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class ProjectAuthMixin(object):
    def get_queryset(self):
        allowed_group_names = self.request.user.groups.all().values_list('name', flat=True)
        return Project.objects.filter(name__in=allowed_group_names)


@method_decorator(login_required, name='dispatch')
class ProjectListView(generic.ListView):
    model = Project
    template_name = 'datapool/project/project_list.html'
    context_object_name = 'projects'
    fields = ['name', 'created']

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     return context


class ProjectCreateView(generic.CreateView):
    model = Project
    template_name = 'datapool/project/project_create.html'
    context_object_name = 'project'
    fields = ['name']

    def get_success_url(self):
        return reverse('datapool:project_list')

#we decorate dispatch, because that is the first function that is called.
@method_decorator(login_required, name='dispatch')
class ProjectDetailView(generic.DetailView):
    model = Project
    template_name = 'datapool/project/project_detail.html'
    context_object_name = 'project'
    fields = ['name', 'created']

    def get_context_data(self, **kwargs):
        # es gibt auch context-processor-middlewares, die immer gewisse sachen in den context schieben.
        # django macht das automatisch zB mit dem user-object
        context = super().get_context_data(**kwargs)
        context['assigned_pools'] = Quota.objects.filter(project=self.object)
        return context


class ProjectUpdateView(generic.UpdateView):
    model = Project
    template_name = 'datapool/project/project_update.html'
    context_object_name = 'project'
    fields = ['name']

    def get_success_url(self):
        kwargs=dict(
            pk = self.object.pk
        )
        return reverse('datapool:project_update', kwargs=kwargs)


class ProjectDeleteView(generic.DeleteView):
    model = Project
    template_name = 'datapool/project/project_delete.html'
    context_object_name = 'project'
    fields = ['name']


    def get_success_url(self):
        return reverse('datapool:project_list')

lrz/lrz_datapool/datapool/templates/datapool/container/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <h1>Create new Container</h1>
    {% if quota  %}
        <h4>On Datapool '<b>{{quota.datapool.name}}</b>' for Project '<b>{{quota.project.name}}</b>'</h4>
    {% else %}
        <h4>for Project '<b>{{ project.name }}</b>'</h4>
    {% endif %}



    <form action="" method="post">
        {% csrf_token %}

        {{ form|crispy }}

        <button class="btn btn-success" type="submit">
            <i class="fa fa-angle-right"></i>
            Create
        </button>
    </form>


{% endblock %}

lrz/lrz_datapool/datapool/templates/datapool/container/delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <h1 class="danger">Delete Container '{{ container.name }}'</h1>

    <form action="" method="post">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">
            <i class="fa fa-trash"></i>
            Yes, delete
        </button>
    </form>


{% endblock %}

lrz/lrz_datapool/datapool/templates/datapool/container/list.html
{% extends 'base.html' %}
{% load i18n %}
{% load space_bar %}

{% block content %}

    <h1>{% trans 'Containers' %}</h1>
    <h4>{% trans 'for Project' %} '<b>{{ project.name }}</b>'
        {% trans 'in Datapool' %}  '<b>{{ datapool.name }}</b>'
    </h4>


    <div>
        <a href="{% url 'datapool:container_create_onQuota' quota.pk %}" class="btn btn-primary">
            <i class="fa fa-plus"></i>
            {% trans 'Create Container' %}
        </a>

        {{ quota|space_barM }}
    </div>


    <table class="table">
        <tr>
            <th>{% trans 'Name' %}</th>
            <th>{% trans 'In Datapool' %}</th>
            <th>{% trans 'size' %}</th>
            <th>{% trans 'used' %}</th>
            <th>{% trans 'Actions' %}</th>
        </tr>
        {% for container in containers %}
            <tr>
                <td>{{ container.name }}</td>
                <td>{{ container.quota.datapool.name }}</td>
                <td>{{ container.size }} {% trans 'Datas' %}</td>
                <td title="Last updated: {{ container.updated|timesince }}">
                    {{ container.used }} {% trans 'Datas' %}
                </td>
                <td>
                    <a href="{% url 'datapool:container_update' container.pk %}" class="btn btn-default">
                        <i class="fa fa-pencil"></i>
                        {% trans 'Edit' %}
                    </a>
                    <a href="{% url 'datapool:container_delete' container.pk %}" class="btn btn-danger">
                        <i class="fa fa-times-circle"></i>
                        {% trans 'Delete' %}
                    </a>
                </td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

lrz/lrz_datapool/datapool/templates/datapool/container/listSnippet.html
{% load i18n %}
{% load space_bar %}


    <h1>{% trans 'Containers' %}</h1>
    <h4>{% trans 'for Project' %} '<b>{{ project.name }}</b>'
        {% trans 'in Datapool' %}  '<b>{{ datapool.name }}</b>'
    </h4>


    <div>
        <a href="{% url 'datapool:container_create_onQuota' quota.pk %}" class="btn btn-primary">
            <i class="fa fa-plus"></i>
            {% trans 'Create Container' %}
        </a>

        {{ quota|space_barM }}
    </div>


    <table class="table">
        <tr>
            <th>{% trans 'Name' %}</th>
            <th>{% trans 'In Datapool' %}</th>
            <th>{% trans 'size' %}</th>
            <th>{% trans 'used' %}</th>
            <th>{% trans 'Actions' %}</th>
        </tr>
        {% for container in containers %}
            <tr>
                <td>{{ container.name }}</td>
                <td>{{ container.quota.datapool.name }}</td>
                <td>{{ container.size }} {% trans 'Datas' %}</td>
                <td title="Last updated: {{ container.updated|timesince }}">
                    {{ container.used }} {% trans 'Datas' %}
                </td>
                <td>
                    <a href="{% url 'datapool:container_update' container.pk %}" class="btn btn-default">
                        <i class="fa fa-pencil"></i>
                        {% trans 'Edit' %}
                    </a>
                    <a href="{% url 'datapool:container_delete' container.pk %}" class="btn btn-danger">
                        <i class="fa fa-times-circle"></i>
                        {% trans 'Delete' %}
                    </a>
                </td>
            </tr>
        {% endfor %}
    </table>

lrz/lrz_datapool/datapool/templates/datapool/container/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <h1>Modify Container '{{ container.name }}'</h1>

    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success" type="submit">
            <i class="fa fa-angle-right"></i>
            Update
        </button>
    </form>


{% endblock %}