lrz/lrz_datapool/datapool/urls.py
from django.conf.urls import url
from datapool import views


urlpatterns = [
    url(r'^$',
        views.main_views.index_view,
        name='index'
        ),

    # D A T A P O O L
    # function-based view
    url(r'^datapool/list/$',
        views.datapool_views.datapool_list_view,
        name='datapool_list'
        ),
    url(r'^datapool/(?P<pk>\d+)/$',
        views.datapool_views.datapool_detail_view,
        name='datapool_detail'
    ),
    # url(r'^datapool/create/$',
    #     views.datapool_views.datapool_create_view,
    #     name='datapool_create'
    #     ),
    # url(r'^datapool/delete/(\d+)/$',
    #     views.datapool_views.datapool_delete_view,
    #     name='datapool_delete'
    #     ),
    #this is a duplicate of the class-based update-view blow
    #url(r'^datapool/updateF/(\d+)/$',
    #    views.datapool_views.datapool_update_view,
    #    name='datapool_update_f'
    #    ),

    # class-based view
    url(r'^datapool/create/$',
        views.datapool_views_cb.Datapool_create_view.as_view(),
        name='datapool_create'
        ),
    url(r'^datapool/delete/(?P<pk>\d+)/$',
        views.datapool_views_cb.Datapool_delete_view.as_view(),
        name='datapool_delete'
    ),
    url(r'^datapool/updateC/(?P<pk>\d+)/$',
        views.datapool_views_cb.Datapool_update_view.as_view(),
        name='datapool_update'
    ),

    # P R O J E C T
    url(r'^project/list/$',
        views.project_views.ProjectListView.as_view(),
        name="project_list"
    ),
    url(r'^project/create/$',
        views.project_views.ProjectCreateView.as_view(),
        name="project_create"
    ),
    url(r'^project/(?P<pk>\d+)/$',
        views.project_views.ProjectDetailView.as_view(),
        name='project_detail'
    ),
    url(r'^project/update/(?P<pk>\d+)/$',
        views.project_views.ProjectUpdateView.as_view(),
        name='project_update'
    ),
    url(r'^project/delete/(?P<pk>\d+)/$',
        views.project_views.ProjectDeleteView.as_view(),
        name='project_delete'
    ),

    # Q U O T A
    url(r'^quota/create/forProject/(?P<project_id>\d+)/$',
        views.quota_views.QuotaCreateView.as_view(),
        name='quota_create'
    ),
    url(r'^quota/update/(?P<pk>\d+)/$',
        views.quota_views.QuotaUpdateView.as_view(),
        name='quota_update'
    ),
    url(r'^quota/delete/(?P<pk>\d+)/$',
        views.quota_views.QuotaDeleteView.as_view(),
        name='quota_delete'
    ),

    # C O N T A I N E R
    url(r'^container/list/Qt/(?P<quotaID>\d+)/$',
        views.container_views.ContainerListView.as_view(),
        name="container_list"
    ),
    url(r'^container/list/Qt/(?P<quotaID>\d+)/asSnippet/$',
        views.container_views.ContainerListSnippetView.as_view(),
        name="container_list_snippet"
    ),
    url(r'^container/create/forProject/(?P<projectID>\d+)/$',
        views.container_views.ContainerCreateView.as_view(),
        name="container_create_forProject"
    ),
    url(r'^container/create/onQuota/(?P<quotaID>\d+)/$',
        views.container_views.ContainerCreateView.as_view(),
        name="container_create_onQuota"
    ),
    url(r'^container/update/(?P<pk>\d+)/$',
        views.container_views.ContainerUpdateView.as_view(),
        name="container_update"
    ),
    url(r'^container/delete/(?P<pk>\d+)/$',
        views.container_views.ContainerDeleteView.as_view(),
        name="container_delete"
    ),

]

lrz/lrz_datapool/project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', auth_views.LoginView.as_view(), name='login'),
    url(r'^logout/', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^datapool/', include('datapool.urls', namespace='datapool')),
    # no namespace here. giving that will break the serializer's 'url'-field magic
    url(r'^datapool_api/', include('datapool_api.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]


# D E B U G   T O O L B A R
from django.conf import settings
from django.conf.urls import include, url

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

lrz/lrz_datapool/datapool/models/container.py
from django.db import models
from django.core.exceptions import ValidationError

class Container(models.Model):
    # the name of the container
    name = models.CharField(max_length=255)
    # the quota the container is connected to
    quota = models.ForeignKey('datapool.quota')
    space = models.PositiveIntegerField(
        help_text="how much space does the container take from the quota"
    )
    # when it was created
    created = models.DateTimeField(auto_now_add=True)
    # how much of the space is used
    used = models.PositiveIntegerField(default=0)
    # when the used-value was last updated
    updated = models.DateTimeField(null=True, blank=True)


    def __str__(self):
        return "Container '{}' on '{}' for '{}', space {} Datas, {} used (updated {})".format(
            self.name,
            self.quota.datapool.name,
            self.quota.project.name,
            self.space,
            self.used,
            self.updated,
        )

    def free(self):
        return self.space - self.used

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        """verify that there is enough space to make this change"""
        spaceLeft = self.quota.spaceLeft()

        if self.pk: # is update
            currentspace = Container.objects.get(pk=self.pk).space
            spaceNeeded = self.space - currentspace
        else: # is create
            spaceNeeded = self.space

        if spaceLeft < spaceNeeded:
            msg = 'Cannot set container-space to {} Datas because that needs {} Datas, ' \
                  'but only {} Datas are available in Quota for Datapool "{}".'
            raise ValidationError(msg.format(self.space, spaceNeeded, spaceLeft, self.quota.datapool.name))

        return super().save(force_insert, force_update, using, update_fields)

lrz/lrz_datapool/datapool/models/project.py
from django.db import models

class Project(models.Model):
    name = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def countDatapoolsLinked(self):
        from datapool.models.quota import Quota
        return Quota.objects.filter(project=self).count()

lrz/lrz_datapool/datapool/views/container_views.py
from django.views import generic
from django.shortcuts import get_object_or_404, reverse

from datapool.models import Datapool
from datapool.models.container import Container
from datapool.models.quota import Quota
from datapool.models.project import Project
from datapool.forms import CreateContainerForm

class ContainerListTemplate(generic.ListView):
    model = Container
    fields = ['name', 'quota', 'space', 'used', 'updated', 'created', ]
    template_name = 'datapool/container/list.html'
    context_object_name = 'containers'

    def dispatch(self, request, *args, **kwargs):
        self.quota = get_object_or_404(Quota, pk=self.kwargs['quotaID'])
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return self.quota.container_set.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['project']  = self.quota.project
        context['datapool'] = self.quota.datapool
        context['quota'] = self.quota
        context['used'] = self.quota.space - self.quota.spaceLeft()
        context['free'] = self.quota.spaceLeft()
        return context


class ContainerListView(ContainerListTemplate):
    pass

class ContainerListSnippetView(ContainerListTemplate):
    template_name = 'datapool/container/listSnippet.html'


class ContainerCreateView(generic.CreateView):
    model = Container
    template_name = 'datapool/container/create.html'
    context_object_name = 'container'
    form_class = CreateContainerForm

    def dispatch(self, request, *args, **kwargs):
        self.quota   = None
        self.project = None

        if 'quotaID' in self.kwargs:
            quotaID = self.kwargs['quotaID']
            self.quota = get_object_or_404(Quota, pk=quotaID)
        elif 'projectID' in self.kwargs:
            self.project = get_object_or_404(Project, pk=self.kwargs.get('projectID'))
        else:
            raise Exception("How did that happen? we should have either quota or project here.")

        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['quota']   = self.quota
        context['project'] = self.project
        return context


    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if self.quota:
            kwargs['instance'] = Container(quota=self.quota)
        return kwargs

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        if self.project:
            form.fields['quota'].queryset = Quota.objects.filter(project_id=self.project)
        return form

    def get_success_url(self):
        if self.project:
            return reverse('datapool:project_detail', kwargs=dict(pk=self.project.id))
        if self.quota:
            return reverse('datapool:container_list', kwargs=dict(quotaID=self.quota.id,))


class ContainerUpdateView(generic.UpdateView):
    model = Container
    fields = ['name', 'quota', 'space', ]
    template_name = 'datapool/container/update.html'
    context_object_name = 'container'
    def get_success_url(self):
        return reverse('datapool:container_list', kwargs=dict(quotaID=self.object.quota.id,))


class ContainerDeleteView(generic.DeleteView):
    model = Container
    fields = ['name', 'quota', 'space', ]
    template_name = 'datapool/container/delete.html'
    context_object_name = 'container'
    def get_success_url(self):
        return reverse('datapool:container_list', kwargs=dict(quotaID=self.object.quota.id,))

lrz/lrz_datapool/datapool/views/datapool_views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from datapool.models import Datapool
from django.forms import modelform_factory
from django.views import generic

allFields=['name', 'description', 'space', 'pool_type', 'owner',]

def datapool_list_view(request):
    pools = Datapool.objects.all()
    context = dict(pools=pools)
    return render(request, 'datapool/datapool/datapool_list.html', context)


def datapool_create_view(request):
    formclass = modelform_factory(Datapool, fields=allFields)

    if request.method == 'POST':
        form = formclass(request.POST)
        if form.is_valid():
            datapool = form.save()
            return redirect(reverse('datapool:datapool_list'))
        else:
            pass # if invalid just fall through to the last return. but now it has error-annotations.
    else:
        form = formclass()

    context = dict(
        form=form,
    )

    return render(request, 'datapool/datapool/datapool_create.html', context)


def datapool_detail_view(request, pk):
    datapool = get_object_or_404(Datapool, pk=pk)
    context = dict(
        datapool = datapool
    )
    return render(request, 'datapool/datapool/datapool_detail.html', context)


def datapool_update_view(request, pk):
    pool = get_object_or_404(Datapool, pk=pk)
    formclass = modelform_factory(Datapool, fields=['name', 'description', 'pool_type', 'owner',])

    if request.method == 'POST':
        form = formclass(request.POST, instance=pool)
        if form.is_valid():
            datapool = form.save()
            return redirect(reverse('datapool:datapool_list'))
        else:
            pass # if invalid just fall through to the last return. but now it has error-annotations.
    else:
        form = formclass(instance=pool)

    context = dict(
        form=form,
        datapool=pool,
    )

    return render(request, 'datapool/datapool/datapool_update.html', context)


def datapool_delete_view(request, pk):
    """This thing instantly deletes instances. beware!"""
    pool = get_object_or_404(Datapool, pk=pk)
    pool.delete()

    return redirect(reverse('datapool:datapool_list'))

lrz/lrz_datapool/datapool/views/datapool_views_cb.py
from django.shortcuts import reverse
from django.views import generic
from datapool.models import Datapool

allFields=['name', 'description', 'space', 'pool_type', 'owner',]

class Datapool_create_view(generic.CreateView):
    model = Datapool
    template_name = 'datapool/datapool/datapool_create.html'
    context_object_name = 'datapool'
    fields = allFields

    def get_success_url(self):
        return reverse('datapool:datapool_list')


class Datapool_update_view(generic.UpdateView):
    model = Datapool
    template_name = 'datapool/datapool/datapool_update.html'
    context_object_name = 'datapool'
    fields = allFields

    def get_success_url(self):
        context = dict(pk=self.object.id)
        return reverse('datapool:datapool_update', kwargs=context)



class Datapool_delete_view(generic.DeleteView):
    model = Datapool
    template_name = 'datapool/datapool/datapool_delete.html'
    context_object_name = 'datapool'
    fields = allFields

    def get_success_url(self):
        return reverse('datapool:datapool_list')

lrz/lrz_datapool/datapool/views/main_views.py
from django.shortcuts import render
from datapool import models as dp_models

# Create your views here.

def index_view(request):

    pools = dp_models.Datapool.objects.all()
    context = dict(
        pools=pools,
    )

    return render(request, 'datapool/index.html', context)

lrz/lrz_datapool/datapool/views/project_views.py
from django.shortcuts import reverse
from django.views import generic
from datapool.models.project import Project
from datapool.models.quota import Quota

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class ProjectAuthMixin(object):
    def get_queryset(self):
        allowed_group_names = self.request.user.groups.all().values_list('name', flat=True)
        return Project.objects.filter(name__in=allowed_group_names)


@method_decorator(login_required, name='dispatch')
class ProjectListView(generic.ListView):
    model = Project
    template_name = 'datapool/project/project_list.html'
    context_object_name = 'projects'
    fields = ['name', 'created']

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     return context


class ProjectCreateView(generic.CreateView):
    model = Project
    template_name = 'datapool/project/project_create.html'
    context_object_name = 'project'
    fields = ['name']

    def get_success_url(self):
        return reverse('datapool:project_list')

#we decorate dispatch, because that is the first function that is called.
@method_decorator(login_required, name='dispatch')
class ProjectDetailView(generic.DetailView):
    model = Project
    template_name = 'datapool/project/project_detail.html'
    context_object_name = 'project'
    fields = ['name', 'created']

    def get_context_data(self, **kwargs):
        # es gibt auch context-processor-middlewares, die immer gewisse sachen in den context schieben.
        # django macht das automatisch zB mit dem user-object
        context = super().get_context_data(**kwargs)
        context['assigned_pools'] = Quota.objects.filter(project=self.object)
        return context


class ProjectUpdateView(generic.UpdateView):
    model = Project
    template_name = 'datapool/project/project_update.html'
    context_object_name = 'project'
    fields = ['name']

    def get_success_url(self):
        kwargs=dict(
            pk = self.object.pk
        )
        return reverse('datapool:project_update', kwargs=kwargs)


class ProjectDeleteView(generic.DeleteView):
    model = Project
    template_name = 'datapool/project/project_delete.html'
    context_object_name = 'project'
    fields = ['name']


    def get_success_url(self):
        return reverse('datapool:project_list')

lrz/lrz_datapool/project/views.py
from django.views import generic

lrz/lrz_datapool/datapool/templates/datapool/project/project_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <h1>Create new Project</h1>

    <a href="{% url 'datapool:project_list' %}" class="btn btn-primary">
        <i class="fa fa-search"></i>
        List Projects
    </a>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success" type="submit">
            <i class="fa fa-angle-right"></i>
            Create
        </button>
    </form>


{% endblock %}

lrz/lrz_datapool/datapool/templates/datapool/project/project_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <h1 class="danger">Delete Project '{{ project.name }}'</h1>

    <a href="{% url 'datapool:project_list' %}" class="btn btn-primary">
        <i class="fa fa-search"></i>
        List Projects
    </a>
    <form action="" method="post">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">
            <i class="fa fa-trash"></i>
            Yes, delete {{ project.name }}
        </button>
    </form>


{% endblock %}

lrz/lrz_datapool/datapool/templates/datapool/project/project_detail.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <h1>{% trans 'Detail for Project' %} '<b>{{project.name}}</b>'</h1>
    <a href="{% url 'datapool:quota_create' project.pk %}">{% trans 'Add new Datapool' %}</a>

    <hr/>

    <h2>{% trans 'Datapools assigned' %}</h2>

    <table class="table">
        <tr>
            <th>{% trans 'Name' %}</th>
            <th>{% trans 'Quota' %}</th>
            <th>{% trans 'Left' %}</th>
            <th>{% trans 'Container count' %}</th>
            <th>{% trans 'Actions' %}</th>
        </tr>
        {% for quota in assigned_pools %}
            <tr>
                <td>{{ quota.datapool.name }}</td>
                <td>{{ quota.space }} {% trans 'Datas' %}</td>
                <td>{{ quota.spaceLeft }} {% trans 'Datas' %}</td>
                <td>{{ quota.container_set.all.count }} {% trans 'Containers' %}</td>

                <td>
                    <a class="btn btn-yellow"  href="{% url 'datapool:container_list' quota.pk %}">
                        <i class="fa fa-database"></i> {% trans 'Manage Containers' %}
                    </a>
                    <a class="btn btn-yellow"  href="{% url 'datapool:quota_update' quota.pk %}">
                        <i class="fa fa-pencil"></i> {% trans 'Edit' %}
                    </a>
                    {% if quota.container_set.all.count %}
                        <button class="btn btn-disabled" disabled title="{% trans 'You cannot delete Quotas that still have containers.' %}">
                            <i class="fa fa-trash"></i> {% trans 'Delete' %}
                        </button>
                    {% else %}
                        <a class="btn btn-danger" href="{% url 'datapool:quota_delete' quota.pk %}">
                            <i class="fa fa-trash"></i> {% trans 'Delete' %}
                        </a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

lrz/lrz_datapool/datapool/templates/datapool/project/project_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}

    <h1>{% trans 'Project Overview' %}</h1>

    <a href="{% url 'datapool:project_create' %}" class="btn btn-primary">
        <i class="fa fa-plus"></i>
        {% trans 'Create Project' %}
    </a>

    <table class="table">
        <tr>
            <th>{% trans 'Name' %}</th>
            <th>{% trans 'Datapools assigned' %}</th>
            <th>{% trans 'Created' %}</th>
            <th>{% trans 'Actions' %}</th>
        </tr>
        {% for item in projects %}
            <tr>
                <td>{{ item.name }}</td>
                <td>{{ item.countDatapoolsLinked }}</td>
                <td>{{ item.created }}</td>
                <td>
                    <a href="{% url 'datapool:project_detail' item.pk %}" class="btn btn-default">
                        <i class="fa fa-clipboard"></i>
                        {% trans 'Manage Datapools and Quotas' %}
                    </a>
                    <a href="{% url 'datapool:project_update' item.pk %}" class="btn btn-default">
                        <i class="fa fa-pencil"></i>
                        {% trans 'Rename' %}
                    </a>
                    {% if item.countDatapoolsLinked %}
                        <button class="btn btn-disabled"
                            disabled
                            title="You cannot delete this Project. There are still Datapools connected. Unlink them first."
                        >
                            <i class="fa fa-times-circle"></i>
                            {% trans 'Delete' %}
                        </button>
                    {% else %}
                        <a href="{% url 'datapool:project_delete' item.pk %}" class="btn btn-danger">
                            <i class="fa fa-times-circle"></i>
                            {% trans 'Delete' %}
                        </a>
                    {% endif %}

                </td>
            </tr>
        {% endfor %}
    </table>


{% endblock %}

lrz/lrz_datapool/datapool/templates/datapool/project/project_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <h1>Modify Project '{{ project.name }}'</h1>

    <a href="{% url 'datapool:project_list' %}" class="btn btn-primary">
        <i class="fa fa-search"></i>
        List Projects
    </a>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success" type="submit">
            <i class="fa fa-angle-right"></i>
            Update
        </button>
    </form>


{% endblock %}