lrz/lrz_datapool/datapool/urls.py
from django.conf.urls import url
from datapool import views


urlpatterns = [
    url(r'^$',
        views.main_views.index_view,
        name='index'
        ),

    # D A T A P O O L
    # function-based view
    url(r'^datapool/list/$',
        views.datapool_views.datapool_list_view,
        name='datapool_list'
        ),
    url(r'^datapool/(?P<pk>\d+)/$',
        views.datapool_views.datapool_detail_view,
        name='datapool_detail'
    ),
    # url(r'^datapool/create/$',
    #     views.datapool_views.datapool_create_view,
    #     name='datapool_create'
    #     ),
    # url(r'^datapool/delete/(\d+)/$',
    #     views.datapool_views.datapool_delete_view,
    #     name='datapool_delete'
    #     ),
    #this is a duplicate of the class-based update-view blow
    #url(r'^datapool/updateF/(\d+)/$',
    #    views.datapool_views.datapool_update_view,
    #    name='datapool_update_f'
    #    ),

    # class-based view
    url(r'^datapool/create/$',
        views.datapool_views_cb.Datapool_create_view.as_view(),
        name='datapool_create'
        ),
    url(r'^datapool/delete/(?P<pk>\d+)/$',
        views.datapool_views_cb.Datapool_delete_view.as_view(),
        name='datapool_delete'
    ),
    url(r'^datapool/updateC/(?P<pk>\d+)/$',
        views.datapool_views_cb.Datapool_update_view.as_view(),
        name='datapool_update'
    ),

    # P R O J E C T
    url(r'^project/list/$',
        views.project_views.ProjectListView.as_view(),
        name="project_list"
    ),
    url(r'^project/create/$',
        views.project_views.ProjectCreateView.as_view(),
        name="project_create"
    ),
    url(r'^project/(?P<pk>\d+)/$',
        views.project_views.ProjectDetailView.as_view(),
        name='project_detail'
    ),
    url(r'^project/update/(?P<pk>\d+)/$',
        views.project_views.ProjectUpdateView.as_view(),
        name='project_update'
    ),
    url(r'^project/delete/(?P<pk>\d+)/$',
        views.project_views.ProjectDeleteView.as_view(),
        name='project_delete'
    ),

    # Q U O T A
    url(r'^quota/create/forProject/(?P<project_id>\d+)/$',
        views.quota_views.QuotaCreateView.as_view(),
        name='quota_create'
    ),
    url(r'^quota/update/(?P<pk>\d+)/$',
        views.quota_views.QuotaUpdateView.as_view(),
        name='quota_update'
    ),
    url(r'^quota/delete/(?P<pk>\d+)/$',
        views.quota_views.QuotaDeleteView.as_view(),
        name='quota_delete'
    ),

    # C O N T A I N E R
    url(r'^container/list/Qt/(?P<quotaID>\d+)/$',
        views.container_views.ContainerListView.as_view(),
        name="container_list"
    ),
    url(r'^container/list/Qt/(?P<quotaID>\d+)/asSnippet/$',
        views.container_views.ContainerListSnippetView.as_view(),
        name="container_list_snippet"
    ),
    url(r'^container/create/forProject/(?P<projectID>\d+)/$',
        views.container_views.ContainerCreateView.as_view(),
        name="container_create_forProject"
    ),
    url(r'^container/create/onQuota/(?P<quotaID>\d+)/$',
        views.container_views.ContainerCreateView.as_view(),
        name="container_create_onQuota"
    ),
    url(r'^container/update/(?P<pk>\d+)/$',
        views.container_views.ContainerUpdateView.as_view(),
        name="container_update"
    ),
    url(r'^container/delete/(?P<pk>\d+)/$',
        views.container_views.ContainerDeleteView.as_view(),
        name="container_delete"
    ),

]

lrz/lrz_datapool/project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', auth_views.LoginView.as_view(), name='login'),
    url(r'^logout/', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^datapool/', include('datapool.urls', namespace='datapool')),
    # no namespace here. giving that will break the serializer's 'url'-field magic
    url(r'^datapool_api/', include('datapool_api.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]


# D E B U G   T O O L B A R
from django.conf import settings
from django.conf.urls import include, url

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

lrz/lrz_datapool/theme/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>DSSlite</title>

    <script type="text/javascript" src="{% static "theme/js/jquery-1.12.1.min.js" %}"></script>
    <script type="text/javascript" src="{% static "theme/bootstrap/js/bootstrap.min.js" %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static "theme/compiled/compiled.css" %}">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>


<div class="container-fluid">
    <div class="page">
        <div id="header">
            <a id="logo">
                <img src="{% static "theme/img/logo.png" %}" class="img-responsive">
            </a>
        </div>
        <div id="nav-main">
            {% include "nav.html" %}
        </div>
        <ol class="breadcrumb">
            {% block breadcrumb %}
                <li class="active">Start</li>
            {% endblock %}
        </ol>
        <div id="content-container">


            <div id="content">
                {% block content %}
                {% endblock %}
            </div>
        </div>
        <div id="footer">
            Footer
        </div>
    </div>
</div>


</body>

</html>

lrz/lrz_datapool/theme/templates/nav.html
{% load staticfiles %}
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'datapool:datapool_list' %}">
                    <i class="fa fa-database"></i>
                    Datapool</a>
                </li>
                <li><a href="{% url 'datapool:project_list' %}">
                    <i class="fa fa-clipboard"></i>
                    Projects</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'admin:index' %}">Administration</a></li>
                <li class="dropdown">
                    {% if request.user.is_authenticated %}
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" >
                            <i class="fa fa-user"></i>
                            {{ request.user }}
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'logout' %}">
                                <i class="fa fa-sign-out"></i>
                                Logout
                            </a></li>
                        </ul>
                    {% else %}
                        <a href="{% url 'login' %}">
                            <i class="fa fa-sign-in"></i>
                            Login
                        </a>
                    {% endif %}
                </li>
            </ul>
        </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
</nav>